AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  xgb-pipeline

  Sample SAM Template for xgbTraining

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  XgbTrainingStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachine/xgb_pipeline.asl.json
      DefinitionSubstitutions:
        DatasetUploadFunctionArn: !GetAtt DatasetUploadFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref DatasetUploadFunction

  DatasetUploadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/dataset_upload/
      Handler: app.lambda_handler
      Runtime: python3.8

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DatasetUploadFunction:
    Description: "Dataset Upload Lambda Function ARN"
    Value: !GetAtt DatasetUploadFunction.Arn
  DatasetUploadFunctionIamRole:
    Description: "Implicit IAM Role created for Dataset Upload Function"
    Value: !GetAtt DatasetUploadFunctionRole.Arn

